'use client'
import Head from 'next/head';
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub} from "react-icons/ai";
import Image from "next/image";
import absPic from "./../../public/PicofMe.jpg";
import coderAcademy from "./../../public/coderacademy.jpg";
import travelByBit from "./../../public/travelbybit.jpg";
import qut from "./../../public/qutLogo.jpg";
import { useState } from "react";

export default function Home() {
  const skipPlugin= process.env.NETLIFY_NEXT_PLUGIN_SKIP;
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head> 
        <title>Abs Portfolio</title>
        <meta name="description" content="Generated by create next js"></meta>
        <link rel='icon' href='./../../public/PicofMe.jpg' />
      </Head> 

      <main className='bg-slate-200 px-10 md:px-20 lg:px-40 dark:bg-gray-800'>
        <section className='min-h-screen'>
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-Overpass text-black dark:text-slate-300">developedByAbs</h1>

            <ul className='flex items-center'>
            <li>
            <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl text-black" />
            </li>
            <li><a className="bg-gradient-to-r from-cyan-600 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-700 font-medium md:text-6xl dark:text-emerald-500">Abs Mohamed</h2>
            <h3 className="text-2xl py-2 text-slate-800 md:text-3xl dark:text-slate-300">Full-Stack Web Developer and Data Scientist</h3>
            <p className="text-md py-5 leading-8 text-gray-700 md:text-xl max-w-xl mx-auto dark:text-slate-300">I'm a software engineer looking to continue my journey of growth after my university degree, coding bootcamp and my internship at TravelbyBit. I'm looking to be a part of an organisation where I will be challenged every day and where I will be working with and learning from skilled developers. Can you help me grow as a developer and satisfy my endless thirst for knowledge?</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-700 dark:text-slate-300 md:text-6xl">
            <a href="https://www.linkedin.com/in/abs-mohamed/"><AiFillLinkedin /></a>
            <a href="https://github.com/absmohamed"><AiFillGithub href="https://www.github.com/absmohamed"/></a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-600 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image class="rounded-lg overflow-hidden" src={absPic} layout="fill" />
          </div>
        </section>

        <section>
          <div className="text-center p-10">
            <h3 className='text-3xl pt-10 text-teal-700 font-medium dark:text-slate-300'>Education & Work Experience:</h3>
            <p className='text-slate-700 text-md py-2 leading-8 dark:text-slate-300'>
              I began my journey into web development starting with my coding bootcamp at <a href="https://coderacademy.edu.au/" className="text-emerald-600 dark:text-emerald-400">Coder Academy</a> which then landed me an intership at <a href="https://www.travelbybit.com/" className="text-emerald-600 dark:text-emerald-400">TravelbyBit</a>. After that, i decided to further my education by pursuing a Bachelor of Information Technology degree majoring in Data Science and Computer Science at <a href="https://www.qut.edu.au/" className="text-emerald-600 dark:text-emerald-400">Queensland University of Technology</a>.
            </p>
            <p className='text-slate-700 text-md py-2 leading-8 dark:text-slate-300'>I offer a wide range of services, including frontend development, backend development, designing and data analytics</p>
          </div>
          <div className="lg:flex gap-10">
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-200 flex-1'>
              <Image className='relative mx-auto' src={coderAcademy} width={175} height={175} />
              <h3 className='text-slate-700 font-medium text-lg pt-8 pb-2 '>Coding Bootcamp</h3>
              <p className='text-gray-800 py-1'>Same coding bootcamp and the same content as the popular accelerated pathway, but at a pace that worked for me. This allowed me to fit study around work commitments and family.</p>
              <h4 className='text-gray-800 py-1'>Bootcamp Duration: 10 months</h4>
              <p className='text-gray-800 py-1'>Qualification: Higher Education Diploma of Information Technology</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-200 flex-1'>
              <Image className='relative mx-auto' src={travelByBit} width={175} height={175} />
              <h3 className='text-slate-700 font-medium text-lg pt-8 pb-2'>TravelbyBit Internship</h3>
              <p className='text-gray-800 py-1'>I did work on the backend and frontend of the TravelbyBit website by adding Frequent Flyer fields to the passenger details form and adding backend validations for those fields. I also added backend validations for the date input to make sure the return date is not before the departure date and that the departure date is not null. Also worked with react datepicker.</p>
              <h4 className='text-gray-800 py-1'>Internship Duration: 1 month</h4>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-200 flex-1'>
              <Image className='relative mx-auto rounded-t-lg' src={qut} width={155} height={155} />
              <h3 className='text-slate-700 font-medium text-lg pt-8 pb-2 '>Bachelor of Information Technology: Data Science & Computer Science Major</h3>
              <p className='text-gray-800 py-1'>In my majors, I learned software development and networking systems. I gained priceless knowledge in specific areas such as information security, networks and communications, intelligent systems, data-centric computing, and user experiences. </p>
              <h4 className='text-gray-800 py-1'>Degree Duration: 2 years and 6 months</h4>
              <p className='text-gray-800 py-1'>Qualification: Bachelor of Information Technology: Data Science & Computer Science Major</p>
            </div>
          </div>
        </section>
        <footer class="bg-slate-200 rounded-lg shadow dark:bg-gray-800">
          <div class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
            <span class="text-sm text-gray-500 relative mx-auto dark:text-gray-300">© 2023 Abs™ All Rights Reserved.
          </span>
          </div>
        </footer>
      </main>
    </div>
  )
}
